# Generated by Django 3.1.1 on 2024-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auction', '0002_auto_20240928_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='priority',
            field=models.IntegerField(default=5, max_length=2),
            preserve_default=False,
        ),
    ]
