# Generated by Django 3.1.1 on 2024-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auction', '0003_auto_20240928_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='priority',
            field=models.IntegerField(default=5, max_length=2),
        ),
    ]
