# Generated by Django 3.1.1 on 2024-09-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auction', '0004_auto_20240928_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
